import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Schema as MongooseSchema, Types } from 'mongoose';
import { RestaurantRole } from '../../common/enums/restaurant-role.enum';
import { Restaurant } from '../../restaurants/schemas/restaurant.schema';
import { User } from '../../users/schemas/user.schema';

// The join between a User and a Restaurant, carrying that user's role
// *for that specific restaurant*. This is what allows one user to belong
// to zero, one, or many restaurants with a different role in each.
//
// Mongo has no native foreign keys, so — unlike the FK columns Postgres
// would enforce — `userId`/`restaurantId` are just ObjectId references
// (`ref:`) that Mongoose can `.populate()` on read. Referential integrity
// (e.g. cascade delete) is an application concern now, not a database one;
// none is implemented yet since it wasn't exercised by any existing code
// path (no delete-user/delete-restaurant flow exists at this stage).
//
// Only `createdAt` is tracked (no `updatedAt`), matching the Prisma model,
// since a membership's role isn't currently updatable after creation.
// collection: 'RestaurantMember' — see user.schema.ts for why this is pinned.
@Schema({ timestamps: { createdAt: true, updatedAt: false }, collection: 'RestaurantMember' })
export class RestaurantMember {
  // Declared explicitly so the timestamp generated by Mongoose is visible to
  // TypeScript when lean() results are consumed by platform services.
  createdAt: Date;

  @Prop({ type: MongooseSchema.Types.ObjectId, ref: User.name, required: true })
  userId: Types.ObjectId;

  @Prop({ type: MongooseSchema.Types.ObjectId, ref: Restaurant.name, required: true })
  restaurantId: Types.ObjectId;

  @Prop({ required: true, enum: RestaurantRole })
  role: RestaurantRole;
}

export type RestaurantMemberDocument = HydratedDocument<RestaurantMember>;
export const RestaurantMemberSchema = SchemaFactory.createForClass(RestaurantMember);

// A user can only have one membership (one role) per restaurant —
// same constraint as the Prisma model's `@@unique([userId, restaurantId])`.
RestaurantMemberSchema.index({ userId: 1, restaurantId: 1 }, { unique: true });

// Explicit indexes on the reference fields — Mongo doesn't auto-index
// them the way Postgres auto-indexes foreign keys, and lookups by either
// side (a user's memberships, or a restaurant's members) are the two
// access patterns AuthService already uses.
RestaurantMemberSchema.index({ userId: 1 });
RestaurantMemberSchema.index({ restaurantId: 1 });
